name: Build

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v3

      - name: Building...
        uses: crazy-max/ghaction-xgo@v1.8.0
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build
          prefix: musicfox
          targets: windows/amd64,windows/arm64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: true
          race: false
          ldflags: -s -w
          buildmode: default

      - name: Show
        run: ls -l build

#      - name: Packaging and uploading asserts...
#        run: tar czf kubectl-karmada-${{ matrix.goos }}-${{ matrix.goarch }}.tgz kubectl-karmada LICENSE

#      - name: Uploading assets...
#        if: ${{ !env.ACT }}
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          body_path: CHANGELOG.md
#          files: |
#            bin/musicfox-
#            LICENSE
