name: Close Issue No Response

on:
  issues:
    types: [closed]
  issue_comment:
    types: [created]
  schedule:
    - cron: '5 * * * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: MBilalShafi/no-response@v0.0.6
        with:
          token: ${{ github.token }}
          daysUntilClose: 7
          responseRequiredLabel: "status: waiting for author's response"
          optionalFollowupLabel: "status: waiting for maintainer's response"
          closeComment: >
            The issue has not been closed due to no response from the author, feel free to reopen
